spring:
  application:
    name: xp-posts
  h2:
    console:
      enabled: true
      path: /h2-console

#  security:
#    user:
#      name: "ali"
#      password: "123"

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

un: local
server:
  port: 8050





