name: Java CI - Dev

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your application code
      - uses: actions/checkout@v4

      # 2️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3️⃣ Grant execute permission for Gradle wrapper
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      # 4️⃣ Build with Gradle
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5️⃣ Login to DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 6️⃣ Build & Push Dev Docker Image
      - name: Build & Push Dev Docker Image
        run: |
          SHA=$(git rev-parse --short HEAD)
          IMAGE_NAME=adenli/xp-posts
          IMAGE_TAG=dev-$SHA
          docker build -t $IMAGE_NAME:sha-$SHA .
          docker tag $IMAGE_NAME:sha-$SHA $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:sha-$SHA
          docker push $IMAGE_NAME:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "✅ Built and pushed: $IMAGE_NAME:$IMAGE_TAG"

      # 7️⃣ Checkout the GitOps repo
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: adenali20/expense-tracker-gitops
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: gitops

      # 8️⃣ Update the image tag in the manifest
      - name: Update image tag in GitOps repo
        run: |
          cd gitops/environments/dev/expense-service
          sed -i "s|adenli/xp-posts:.*|adenli/xp-posts:${IMAGE_TAG}|" deployment-service.yml

      # 9️⃣ Commit and push the change
      - name: Commit and push changes
        run: |
          cd gitops
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update dev image tag to ${IMAGE_TAG}"
          git push origin main
